language: python
python:
  - 2.6
  - 2.7
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtest-exception-perl libtest-output-perl libdevel-cover-perl acl
  - pip install codecov
script:
  - scons test
after_success:
  - codecov
