language: python
python:
  - 2.6
  - 2.7
  - 3.5
install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libtest-exception-perl libtest-output-perl libdevel-cover-perl acl
script:
  - scons test
